export const EVENTS = {
  ON_START: 'ON_START',
  ON_BREAK: 'ON_BREAK',
  ON_FINISH: 'ON_FINISH',
  ON_COMPLETE: 'ON_COMPLETE',
  ON_NEXT: 'ON_NEXT',
  ON_TOOMANYATTEMPTS: 'ON_TOOMANYATTEMPTS',
  ON_ERROR: 'ON_ERROR',
  ON_ERRORBREAK: 'ON_ERRORBREAK',
  ON_TOOMANYERRORS: 'ON_TOOMANYERRORS',
  ON_INTERVALERROR: 'ON_INTERVALERROR',
} as const;
